[system]
id = "6f6ab2"
template = "task"
state = "done"
created_at = "2026-02-20T03:52:41Z"
updated_at = "2026-02-20T04:10:16Z"
created_by = "tom"

[fields]
description = "first pass looking for code smells"
exercise = "1"
title = "First pass code smells"

[labels]
tags = []

[edges]
blocks = ["10620e"]

[history]

[[history.entries]]
timestamp = "2026-02-20T03:52:41Z"
from = ""
to = "draft"
by = "tom"
note = "Node created"

[[history.entries]]
timestamp = "2026-02-20T03:54:25Z"
from = "draft"
to = "active"
by = "tom"
note = "Transition: activate"

[[history.entries]]
timestamp = "2026-02-20T04:10:16Z"
from = "active"
to = "done"
by = "tom"
note = "Transition: done"
